# -*- coding: utf-8 -*-
"""Encoder/Decoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NFSxneLYkwodTfwa6raJrMafe67qg4l

**Importing libraries**
"""

# ── 1. Import Libraries ──────────────────────────────────────
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import layers, models, Model
from tensorflow.keras.datasets import mnist

print(f"TensorFlow version: {tf.__version__}")
print(f"NumPy version:      {np.__version__}")

"""**Load** **Dataset**"""

(x_train, _), (x_test, _) = mnist.load_data()

print(f"Train shape before preprocessing: {x_train.shape}")
print(f"Test  shape before preprocessing: {x_test.shape}")

"""**Preprocess Data**"""

# Normalize pixel values to [0, 1]
x_train = x_train.astype("float32") / 255.0
x_test  = x_test.astype("float32")  / 255.0

# Flatten 28×28 images → 784-dimensional vectors
x_train = x_train.reshape(-1, 784)
x_test  = x_test.reshape(-1, 784)

print(f"Train shape after  preprocessing: {x_train.shape}")
print(f"Test  shape after  preprocessing: {x_test.shape}")

"""**Build Encoder**"""

# Reduces 784 → 128 → 64 → 32 (latent space)
encoder_input = layers.Input(shape=(784,), name="encoder_input")
x = layers.Dense(128, activation="relu", name="enc_dense_1")(encoder_input)
x = layers.Dense(64,  activation="relu", name="enc_dense_2")(x)
latent = layers.Dense(32, activation="relu", name="latent_space")(x)

encoder = Model(encoder_input, latent, name="Encoder")
encoder.summary()

"""**Build** **Decoder**"""

# Reconstructs 32 → 64 → 128 → 784
decoder_input = layers.Input(shape=(32,), name="decoder_input")
x = layers.Dense(64,  activation="relu",    name="dec_dense_1")(decoder_input)
x = layers.Dense(128, activation="relu",    name="dec_dense_2")(x)
decoder_output = layers.Dense(784, activation="sigmoid", name="decoder_output")(x)

decoder = Model(decoder_input, decoder_output, name="Decoder")
decoder.summary()

"""**conbine**"""

autoencoder_input = layers.Input(shape=(784,), name="autoencoder_input")
encoded = encoder(autoencoder_input)
decoded = decoder(encoded)

autoencoder = Model(autoencoder_input, decoded, name="Autoencoder")
autoencoder.summary()

"""**Compile Model**"""

autoencoder.compile(
    optimizer="adam",
    loss="binary_crossentropy",   # suitable for pixel values in [0, 1]
    metrics=["mse"]
)

"""**Training **"""

EPOCHS     = 20
BATCH_SIZE = 256

history = autoencoder.fit(
    x_train, x_train,          # input = target (reconstruction task)
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    validation_data=(x_test, x_test),
    verbose=1
)

"""**Visualization**"""

from PIL import Image
plt.figure(figsize=(8, 4))
plt.plot(history.history["loss"],     label="Train Loss")
plt.plot(history.history["val_loss"], label="Val   Loss")
plt.title("Autoencoder Training & Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Binary Cross-Entropy Loss")
plt.legend()
plt.tight_layout()
plt.savefig("training_loss.png", dpi=150)
plt.show()

print("Saved: training_loss.png")

n_samples = 10                               # number of images to display
reconstructed = autoencoder.predict(x_test[:n_samples])

fig, axes = plt.subplots(2, n_samples, figsize=(18, 4))
fig.suptitle("Top row: Original  |  Bottom row: Reconstructed", fontsize=13)

for i in range(n_samples):
    # Original
    axes[0, i].imshow(x_test[i].reshape(28, 28), cmap="gray")
    axes[0, i].axis("off")
    axes[0, i].set_title("Orig", fontsize=8)

    # Reconstructed
    axes[1, i].imshow(reconstructed[i].reshape(28, 28), cmap="gray")
    axes[1, i].axis("off")
    axes[1, i].set_title("Recon", fontsize=8)

plt.tight_layout()
plt.savefig("reconstruction.png", dpi=150)
plt.show()
plt.imshow(Image.open("reconstruction.png"))
plt.show()
print("Saved: reconstruction.png")

"""**Test Set**"""

test_loss, test_mse = autoencoder.evaluate(x_test, x_test, verbose=0)
print(f"\nTest Loss (Binary Cross-Entropy) : {test_loss:.4f}")
print(f"Test MSE                          : {test_mse:.4f}")

"""**Adding PCA to reduce dimensions**"""

from sklearn.decomposition import PCA

latent_vectors = encoder.predict(x_test)          # shape (10000, 32)
_, (_, y_test) = mnist.load_data()                # reload labels for colouring

pca = PCA(n_components=2)
latent_2d = pca.fit_transform(latent_vectors)

plt.figure(figsize=(8, 7))
scatter = plt.scatter(
    latent_2d[:, 0], latent_2d[:, 1],
    c=y_test, cmap="tab10", s=3, alpha=0.6
)
plt.colorbar(scatter, label="Digit class")
plt.title("2-D PCA of Latent Space (coloured by digit)")
plt.xlabel("PC 1")
plt.ylabel("PC 2")
plt.tight_layout()
plt.savefig("latent_space_pca.png", dpi=150)
plt.show()
print("Saved: latent_space_pca.png")